### ISSUE TITLE
Cannot find path ...\temp\module\module.psd1

### ISSUE THREAD

**Issue by carlosjourdan** [deadlydog/AzureArtifactsPowerShellModuleHelper#17]
When installing a module through Install-AzureArtifactsModule I get the error below 

Install-Package: C:\Users\username\Documents\PowerShell\Modules\PowerShellGet\2.2.4.1\PSModule.psm1:9709:34
Line |
9709 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find the path 'C:\Users\username\Temp\1788469765\ModuleName.0.0.666\ModuleName.psd1' because it does not exist.

**Comment by deadlydog** [comment]
Can you show some code of how you are installing the module, and then trying to access it?

**Comment by carlosjourdan** [comment]
Nevermind, the psd1 file was messed up on my side. Worked perfectly after fixing it.
