### ISSUE TITLE
Update references to [System.Security.Principal.WindowsIdentity]::GetCurrent().Name to be Cross-Platform

### ISSUE THREAD

**Issue by jswright91** [deadlydog/AzureArtifactsPowerShellModuleHelper#21]
https://github.com/deadlydog/AzureArtifactsPowerShellModuleHelper/blob/6627c0197149939501e59cc1b422ebcb126854b5/src/AzureArtifactsPowerShellModuleHelper/AzureArtifactsPowerShellModuleHelper.psm1#L229

Can we please update these references to get the username from whoami, vs The WindowsIdentity principal?

[Other ways to get the current user in powershell](https://shellgeek.com/get-current-user-name-in-powershell/)

**Comment by deadlydog** [comment]
This issue should be addressed in version 2.4.2. Thanks for the suggestion 👍  If it's still an issue let me know. Thanks!
